# Generated by Django 5.2.3 on 2025-07-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hobbies_and_interests',
            new_name='favourite_genres',
        ),
    ]
