# Generated by Django 5.2.3 on 2025-07-14 09:33

import personal_bookshelf.bookshelf.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_rename_hobbies_and_interests_customuser_favourite_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/', validators=[personal_bookshelf.bookshelf.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
