# Generated by Django 5.2.3 on 2025-07-07 13:51

import personal_bookshelf.bookshelf.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='article_covers/default_article_cover.jpg', upload_to='article_covers/', validators=[personal_bookshelf.bookshelf.validators.validate_image_extension]),
        ),
    ]
