# Generated by Django 5.2.3 on 2025-06-24 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction'), ('biography', 'Biography'), ('history', 'History'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('self-help', 'Self-help'), ('other', 'Other')], max_length=20, verbose_name='Genre')),
                ('description', models.TextField()),
                ('review', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
