# Generated by Django 5.2.3 on 2025-06-29 13:34

import personal_bookshelf.bookshelf.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='static/images/', validators=[personal_bookshelf.bookshelf.validators.validate_image_extension]),
        ),
    ]
