# Generated by Django 5.2.3 on 2025-06-29 14:13

import personal_bookshelf.bookshelf.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_covers/default_cover.jpg', upload_to='book_covers/', validators=[personal_bookshelf.bookshelf.validators.validate_image_extension]),
        ),
    ]
