# Generated by Django 5.2.3 on 2025-08-08 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_alter_bookrating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookrating',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='unique_book_user_rating'),
        ),
    ]
